models/Post.php
<?php
namespace app\models;


use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * Модель публикации в блоге
 *
 * Class Post
 * @package app\models
 * @property int $id идентификатор публикации
 * @property string $slug uri для seo
 * @property string $title заголовок публикации
 * @property string $content содержимое публикации
 * @property string $image основная картинка поста
 * @property string $summary краткое содержание публикации, для вывода в ленте
 * @property string $description описание публикации, для вывода в meta-тэгах
 * @property string $keywords ключевые слова публикации, для вывода в meta-тэгах
 * @property int $created_at служебное поле = время создания публикации
 * @property int $updated_at служебное поле = время последнего изменения публикации
 * @property Tag[] $tags автоматическое поле - список тегов назначенных публикации
 *
 *
 * @see Post::getIntro()
 * @property string intro - генерируемое через аксессор поле, краткого содержания.
 *
 *
 * @see Post::getSmallIntro()
 * @property string smallIntro - генерируемое через аксессор поле, соедржания для списка последних публикаций
 *
 */
class Post extends ActiveRecord
{

    /**
     * @var Tag[] - служебное поле, для хранения переназначенных тегов
     */
    protected $_tags = [];


    /**
     * Helper для поиска публикации по URI, по аналогии с findOne($id)
     *
     * @param $slug
     * @return static
     */
    public static function findBySlug($slug)
    {
        return self::findOne(['slug' => $slug]);
    }

    /**
     * Правила валидации
     *
     * @return array
     */
    public function rules()
    {
        return [
            [[
                'title',
                'content',
                'summary',
                'description',
                'keywords',
                'image',
                'slug',
                'tagsLine'
            ], 'trim'],
            [['title', 'content'], 'required'],
            ['slug', 'checkSlug'],
        ];
    }

    /**
     * Проверка на потоврение slug (URI). Используется при ajax запросе
     *
     * @param $attribute
     * @param $params
     */
    public function checkSlug($attribute, $params)
    {
        $post = self::findBySLug($this->slug);
        if (!empty($post) && $post->id != $this->id)
            $this->addError('slug', \Yii::t('blog', 'slug {slug} is already used by {page}',
                ['slug' => $post->slug, 'page' => $post->title]
            ));
    }


    /**
     * Аксессор для получения краткого содержания статьи
     * @return string
     */
    public function getIntro()
    {
        if (!empty($this->summary))
            return $this->summary;

        $content = mb_substr(strip_tags($this->content, '<br><p>'), 0, 1024);
        return mb_strlen($content) == 1024 ? mb_substr($content, 0, mb_strrpos($content, ' ')) . '...' : $content;
    }


    /**
     * Аксессор для получения описания статьи, при выводе в боковой панели
     *
     * @return string
     */
    public function getSmallIntro()
    {
        if (!empty($this->description))
            return $this->description;

        $content = mb_substr(strip_tags($this->content, '<br><p>'), 0, 255);
        return mb_strlen($content) == 255 ? mb_substr($content, 0, mb_strrpos($content, ' ')) . '...' : $content;
    }


    public static function tableName()
    {
        return "posts";
    }


    /**
     * аксессор, для установки переопределенных тегов
     * @param array $_tags
     */
    public function setTags($_tags = [])
    {
        $this->tags = $_tags;
    }

    /**
     * Получение списка связанных с публикацией тегов
     * @return Tag[]|ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::class, ['id' => 'tag_id'])->viaTable('post_tag', ['post_id' => 'id']);
    }


    /**
     * Хук перед сохранением, если пришел пустой slug, тогда устанавливаем в null, чтобы не
     * возникало конфликтов с остальными записями.
     *
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if (empty($this->slug))
            $this->slug = null;

        return parent::beforeSave($insert);
    }

    /**
     * Хук после сохранения объекта, если теги были переопределены,
     * тогда производится обновление связей
     *
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        // Если менялся набор тегов
        if (!empty($this->_tags))
            $this->updateTags(); // Тогда обновляем теги

        parent::afterSave($insert, $changedAttributes);
    }


    /**
     * Внутренныяя функция обновления связей с тегами
     */
    protected function updateTags()
    {
        $vals = [];
        PostTags::deleteAll(['post_id' => $this->id]);
        foreach ($this->_tags as $tag) {
            $vals[$tag->id] = [$this->id, $tag->id];
        }

        $this->getDb()
            ->createCommand()
            ->batchInsert(PostTags::tableName(), ['post_id', 'tag_id'], $vals)->execute();

    }


    /**
     * Функция для интеграции с интерфейсом приложения.
     * Получаем список тегов в строке, разделенный запятыми.
     *
     * @return string
     */
    public function getTagsLine()
    {
        $line = [];
        foreach ($this->tags as $tag) {
            $line[] = $tag->name;
        }
        return implode(', ', $line);
    }


    /**
     * Функция интеграции с интерфейсом прилоежния.
     * Восстанавливаем список тегов из строки. При необходимости создает новые.
     *
     * @param string $tags
     */
    public function setTagsLine($tags = '')
    {
        if (empty($tags))
            return;
        $tagsName = explode(',', $tags);
        foreach ($tagsName as $tagName) {
            $this->_tags[] = Tag::findOrCreate(trim($tagName));
        }
    }


    /**
     * Получение объекта запроса описывающий ленту публикаций сайта
     *
     * @return ActiveQuery
     */
    public static function getFeed()
    {
        return self::find()->orderBy(['updated_at' => SORT_DESC])->with('tags');
    }


    /**
     * Обработчики событий
     *  - Обрабатываем события перед сохранением для установки времени создания и последней модификации.
     *
     *
     * @return array
     */
    public function behaviors()
    {
        parent::behaviors();
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at']
                ]
            ]
        ];
    }


    /**
     * Метод для интеграции с интерфейсом - получение пераметров навигации,
     * в зависимости от наличия slug в объекте публикации.
     *
     * @return array
     */
    public function getNavParams()
    {
        return empty($this->slug) ? ['id' => $this->id] : ['slug' => $this->slug];
    }
}

controllers/BlogController.php
<?php
/**
 * Created by PhpStorm.
 * User: ruvam
 * Date: 10.12.2016
 * Time: 0:35
 */

namespace app\controllers;


use app\common\Controller;
use app\models\Post;
use app\models\Tag;
use Yii;
use yii\data\Pagination;
use yii\db\ActiveRecord;
use yii\web\NotFoundHttpException;

/**
 * Публичный контроллер записей блога. Отвечает за демонстрацию
 * списков публикаций и отдельных записей
 *
 * Class BlogController
 * @package app\controllers
 */
class BlogController extends Controller
{
    /**
     * Отображение списка публикаций упорядоченных по дате добавления
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->title = Yii::t('blog', 'list of publications');
        $posts = Post::getFeed();

        $pages = new Pagination($this->paginationOptions([
            'totalCount' => $posts->count()
        ]));


        $posts = $posts
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', compact('posts', 'pages'));
    }

    /**
     * Просмотр отдельной публикации
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView()
    {
        $id = $this->get('id');
        $slug = $this->get('slug');
        $post = empty($slug) ? Post::findOne($id) : Post::findBySlug($slug);

        if (empty($post))
            throw new NotFoundHttpException(\Yii::t('blog', 'Post with ID={id} not found', ['id' => $id]));

        return $this->render('view', compact('post'));
    }


    /**
     * Вывод списка публикаций по тегу
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionTag()
    {
        $tagName = $this->get('tag');
        $tag = Tag::findOne(['name' => $tagName]);
        if(empty($tag))
            throw new NotFoundHttpException(\Yii::t('blog', 'now publications for tag {tag}', ['tag' => $tagName]));

        $query = $tag->getPosts()->with('tags')->orderBy(['updated_at' => SORT_DESC]);


        $pages = new Pagination($this->paginationOptions([
            'totalCount' => $query->count()
        ]));


        $posts = $query
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', compact('posts', 'pages'));
    }


    /**
     * Получение общих настроек пагинации для контроллера
     *
     * @param array $additional
     * @return array
     */
    protected function paginationOptions($additional = [])
    {
        return array_merge([
            // Количество элементов берется из настроек
            'pageSize' => Yii::$app->settings->get('SiteSettings.postsPerPage'),
            'forcePageParam' => false,
            'pageSizeParam' => false
        ], $additional);
    }



}

views/blog/index.php
<?php
/** @var \app\models\Post[] $posts */
use app\components\LastPublicationsWidget;
use app\components\PopularTagsWidget;
use app\components\RandomQuoteWidget;
use yii\helpers\Html;
use yii\helpers\Url;
use app\materialize\LinkPager;

?>
<div class="row">
    <div class="col hide-on-med-and-down l3 right">
        <?= LastPublicationsWidget::widget(['count' => 6]); ?>
        <p></p>
        <?= RandomQuoteWidget::widget(); ?>

        <p>&nbsp;</p>
        <?= PopularTagsWidget::widget([]); ?>
    </div>
    <div class="col l9 m12">
        <?php foreach ($posts as $post): ?>
            <div class="card post">

                <?php if (!empty($post->image)): ?>
                    <div class="card-image valign-wrapper">

                        <?= Html::img($post->image); ?>

                        <span class="card-title">
                            <a href="<?= Url::to(array_merge(['blog/view'], $post->navParams)) ?>">
                                <?= $post->title; ?>
                            </a>
                            <small>Опубликовано <a href="#">admin</a> <?= date('H:i', $post->updated_at); ?></small>
                        </span>
                    </div>
                <?php endif; ?>
                <div class="card-content">
                    <?php if (empty($post->image)): ?>
                        <span class="card-title">
                            <a href="<?= Url::to(array_merge(['blog/view'], $post->navParams)) ?>">
                                <?= $post->title; ?>
                            </a>
                    <small>Опубликовано <a href="#">admin</a> <?= date('H:i', $post->updated_at); ?></small>
                </span>
                    <?php endif; ?>
                    <?= $post->intro; ?>
                </div>
                <div class="card-action">
                    <span>Тэги: </span>
                    <?php foreach ($post->tags as $tag): ?>
                        <small>
                            <a href="<?= Url::to(['blog/tag', 'tag' => $tag->name]); ?>" class="waves-effect text-deep-purple text-darken-1">
                                <?= $tag->name; ?>
                            </a>
                        </small>
                    <?php endforeach; ?>

                    <a href="<?= Url::to(array_merge(['blog/view'], $post->navParams)) ?>"
                       class="right purple-text waves-effect">
                        <?= \Yii::t('blog', 'More info'); ?>
                    </a>
                    <div class="clearfix"></div>
                </div>
            </div>
        <?php endforeach; ?>


        <div class="center">
            <?= LinkPager::widget(['pagination' => $pages]); ?>
        </div>
    </div>

</div>

views/blog/view.php
<?php
use app\components\LastPublicationsWidget;
use app\components\PopularTagsWidget;
use app\components\RandomQuoteWidget;
use yii\helpers\Html;
use yii\helpers\Url;

/** @var \app\models\Post $post */
?>
<div class="row">
    <div class="col hide-on-med-and-down l3 right">
        <?= LastPublicationsWidget::widget(['count' => 6]); ?>
        <p> </p>
        <?= RandomQuoteWidget::widget(); ?>

        <p>&nbsp;</p>
        <?= PopularTagsWidget::widget([]); ?>
    </div>
    <div class="col l9 m12">
            <div class="card post">

                <?php if (!empty($post->image)): ?>
                    <div class="card-image valign-wrapper">
                        <?= Html::img($post->image); ?>
                        <span class="card-title">
                    <span><?= $post->title; ?></span>
                    <small>Опубликовано <a href="#">admin</a> <?= date('H:i', $post->updated_at); ?></small>
                </span>
                    </div>
                <?php endif; ?>
                <div class="card-content">
                    <?php if(empty($post->image)): ?>
                        <span class="card-title">
                    <span><?= $post->title; ?></span>
                    <small>Опубликовано <a href="#">admin</a> <?= date('H:i', $post->updated_at); ?></small>
                </span>
                    <?php endif; ?>
                    <?= $post->content; ?>
                </div>
                <hr>
                <div class="card-content">
                    <?php foreach($post->tags as $tag): ?>
                        <a href="<?= Url::to(['blog/tag', 'tag' => $tag->name]); ?>" class="chip">
                            <?= $tag->name; ?>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
    </div>
</div>